baseURL = 'https://embeddingbits.is-a.dev/'
languageCode = 'en-us'
title = "eBits Blog"
theme = 'typo'

googleAnalytics = "G-KP0G8R8WE2"
enableRobotsTXT = true

[taxonomies]
tag = 'tags'

[outputs]
home = ["html", "rss"]
section = ["html", "rss"]
taxonomy = ["html", "rss"]

[params]
# Meta description
description = "Thoughts and Expressions"
author = "Amiitesh TSP"
email = "tspamiitesh@gmail.com"
rssLimit = 50

# Appearance settings
theme = 'dark'
colorPalette = 'gruvebox'
hideHeader = false

language = 'en'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'
showFooter = true
footerContent = """
Copyright © 2025 Amiitesh TSP.
"""

# Breadcrumbs
[params.breadcrumbs]
enabled = true

# Social icons
[[params.social]]
name = "github"
url = "https://github.com/embeddingbits"

[[params.social]]
name = "codeberg"
url = "https://codeberg.org/embeddingbits"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/amiitesh-pradeep-kumar-582bb831a/"

[[params.social]]
name = "instagram"
url = "https://instagram.com/tspamiitesh"

[[params.social]]
name = "mastodon"
url = "https://mastodon.social/@ebits"

[[params.social]]
name = "medium"
url = "https://medium.com/@tspamiitesh"

# Main menu pages
[[params.menu]]
name = "posts"
url = "/tech"

[[params.menu]]
name = "my_software"
url = "/software"

[[params.menu]]
name = "tags"
url = "/tags"

[[params.menu]]
name = "rss"
url = "/index.xml"

[permalinks]
tech = '/tech/:slug'

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'gruvbox'
