baseURL = 'https://embeddingbits.is-a.dev/'
languageCode = 'en-us'
title = "eBits Blog"
theme = 'typo'

googleAnalytics = "G-KP0G8R8WE2"
enableRobotsTXT = true

[taxonomies]
tag = 'tags'

[outputs]
home = ["html", "rss"]
section = ["html", "rss"]

[params]
# Meta description
description = "Thoughts and Expressions"
mainSections = ["posts"]

# Appearance settings
theme = 'dark'
colorPalette = 'gruvebox'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = "Hi, I'm eBits"
homeIntroContent = """
Hello, I’m Amiitesh, a B.Tech student specializing in Electronics and Computer Engineering 

I spend most of my time messing around with Linux, programming, and exploring systems like operating systems, VLSI, and embedded systems. Apart from tech, I like reading, music, and writing.

I use [Arch Linux](https://archlinux.org) currently and enjoy ricing my setup. You can check out my [dotfiles](https://github.com/embeddingbits/arch_dotfiles). 

I’m also into Free and Open Source Software (FOSS). I like the idea of open collaboration and contribute to my open source projects whenever I could. You can check out some of my [software](https://github.com/embeddingbits/) and software that I use [here](https://embeddingbits.is-a.dev/software).

I write blogs about what I learn, things I find interesting, and ideas I’m experimenting with.

+ Email: [tspamiitesh@gmail.com](tspamiitesh@gmail.com)
+ Discord: [eBits](https://discord.com/users/1312819280018018374)
+ Matrix: [@embeddingbits:matrix.org](@embeddingbits:matrix.org)

"""

language = 'en'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'
showFooter = true
footerContent = """
Copyright © 2025 Amiitesh TSP.
"""

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "github"
url = "https://github.com/embeddingbits"

[[params.social]]
name = "codeberg"
url = "https://codeberg.org/embeddingbits"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/amiitesh-pradeep-kumar-582bb831a/"

[[params.social]]
name = "instagram"
url = "https://instagram.com/tspamiitesh"

[[params.social]]
name = "mastodon"
url = "https://mastodon.social/@ebits"

[[params.social]]
name = "medium"
url = "https://medium.com/@tspamiitesh"

# Main menu pages
[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "my_software"
url = "/software"

[[params.menu]]
name = "tags"
url = "/tags"

[[params.menu]]
name = "rss"
url = "/index.xml"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'gruvbox'
