baseURL = 'https://embeddingbits.is-a.dev/'
languageCode = 'en-us'
title = "eBits Base"
theme = 'typo'
enableRobotsTXT = true

[taxonomies]
tag = 'tags'

[outputs]
home = ["html", "rss"]
section = ["html", "rss"]
taxonomy = ["html", "rss"]

[params]
# Meta description
description = "Thoughts and Expressions"
author = "Amiitesh TSP"
email = "tspamiitesh@gmail.com"
rssLimit = 50
# Appearance settings
theme = 'dark'
colorPalette = 'gruvebox'
hideHeader = false

language = 'en'

# Homepage
homeCollectionTitle = 'Posts'
homeCollection = 'tech'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'
showFooter = true
footerContent = """
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;VIT webring 
<br>
<a href="https://webring-vit.vercel.app/redirect?from=embeddingbits&dir=prev">←</a>
<a href="https://webring-vit.vercel.app/random">random site</a>
<a href="https://webring-vit.vercel.app/redirect?from=embeddingbits&dir=next">→</a>
"""

# Breadcrumbs
[params.breadcrumbs]
enabled = true

# Social icons
[[params.social]]
name = "codeberg"
url = "https://codeberg.org/embeddingbits"

[[params.social]]
name = "github"
url = "https://github.com/embeddingbits"

[[params.social]]
name = "mastodon"
url = "https://mastodon.social/@ebits"

[[params.social]]
name = "matrix"
url = "https://matrix.to/#/@embeddingbits:matrix.org"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/amiitesh-pradeep-kumar-582bb831a/"

[[params.social]]
name = "instagram"
url = "https://instagram.com/tspamiitesh"

# Main menu pages
[[params.menu]]
name = "posts"
url = "/tech"

[[params.menu]]
name = "resume"
url = "/resume"

[[params.menu]]
name = "my_software"
url = "/software"

[[params.menu]]
name = "tags"
url = "/tags"

[[params.menu]]
name = "rss"
url = "/index.xml"

[params.umami]
enable = true
websiteId = "cd6448d2-05fa-46d8-978e-02140c4b5470"
jsLocation = "https://cloud.umami.is/script.js"

# Syntax highlight on code blocks
[markup]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = 'gruvbox'
